export const SEARCH_MOVIE_BY_NAME_REQUEST = 'SEARCH_MOVIE_BY_NAME_REQUEST';
export const SEARCH_MOVIE_BY_NAME_SUCCESS = 'SEARCH_MOVIE_BY_NAME_SUCCESS';
export const SEARCH_MOVIE_BY_NAME_FAILURE = 'SEARCH_MOVIE_BY_NAME_FAILURE';
export const SEARCH_MOVIE_BY_NAME = {
  SUCCESS: SEARCH_MOVIE_BY_NAME_SUCCESS,
  FAILURE: SEARCH_MOVIE_BY_NAME_FAILURE,
  REQUEST: SEARCH_MOVIE_BY_NAME_REQUEST
};

export const GET_POPULAR_MOVIES_REQUEST = 'GET_POPULAR_MOVIES_REQUEST';
export const GET_POPULAR_MOVIES_SUCCESS = 'GET_POPULAR_MOVIES_SUCCESS';
export const GET_POPULAR_MOVIES_FAILURE = 'GET_POPULAR_MOVIES_FAILURE';
export const GET_POPULAR_MOVIES = {
  SUCCESS: GET_POPULAR_MOVIES_SUCCESS,
  FAILURE: GET_POPULAR_MOVIES_FAILURE,
  REQUEST: GET_POPULAR_MOVIES_REQUEST
};

export const REORDER_MOVIES = 'REORDER_MOVIES';
export const ADD_TO_QUEUE = 'ADD_TO_QUEUE';
export const REMOVE_FROM_QUEUE = 'REMOVE_FROM_QUEUE';